# kinesis_xml_data.py

input_records = [
    {
        "input_record": '<?xml version="1.0" encoding="UTF-8" standalone="yes"?><connoteMsg id="2470395525_TDF"><connote action="UN"><consignmentNumber>2470395525</consignmentNumber><actionDate>2025-04-28T19:59:33+10:00</actionDate><splInstructions>Special Instruction - Automation</splInstructions><shipDate>2025-04-28T00:00:00+10:00</shipDate><senderAccount>L21536</senderAccount><senderName>Aarohi Agency</senderName><senderAddress><addressLine1>Lane A</addressLine1><suburb>PARLIAMENT HOUSE</suburb><state>SA</state><country>AU</country><postCode>5000</postCode></senderAddress><senderMobile>61-412345678</senderMobile><senderPhone>61-412345678</senderPhone><receiverName>GEETIKA</receiverName><receiverAddress><addressLine1>Address Line 1</addressLine1><addressLine2>Address Line 2</addressLine2><suburb>MELBOURNE WHARF</suburb><state>VIC</state><country>AU</country><postCode>3000</postCode></receiverAddress><receiverMobile>61-412345678</receiverMobile><receiverPhone>61-412345678</receiverPhone><involvedParties><partyRole>billTo</partyRole><partyAccount>L21536</partyAccount><partyAddress><addressLine1>Lane A</addressLine1><suburb>PARLIAMENT HOUSE</suburb><state>SA</state><country>AU</country><postCode>5000</postCode></partyAddress></involvedParties><totalPallets>0</totalPallets><totalItems>1</totalItems><totalCubic UOM="m3">0.001</totalCubic><totalWeight UOM="Kg">50</totalWeight><isFood>false</isFood><serviceType>Express</serviceType><serviceCode>E</serviceCode><mode>ROAD</mode><busunit>TNQX</busunit><containsDangerousGoods>false</containsDangerousGoods><pickupManifestId>MYT1110199</pickupManifestId><additionalAttributes><attribName>atl</attribName><attribValue>false</attribValue></additionalAttributes><additionalAttributes><attribName>tesFlg</attribName><attribValue>false</attribValue></additionalAttributes><additionalAttributes><attribName>tesAmt</attribName><attribValue>0.0</attribValue></additionalAttributes><additionalAttributes><attribName>isGlencoreShipment</attribName><attribValue>true</attribValue></additionalAttributes><additionalAttributes><attribName>purchaseOrder</attribName><attribValue>PO-2025042807590040 12345</attribValue></additionalAttributes></connote><srcSystem>TW</srcSystem><origin>MYTOLL</origin></connoteMsg>',
        "TS": "2025-04-28T10:55:45.865"
    },
    {
        "input_record": '<?xml version="1.0" encoding = "UTF-8" ?>  <connoteMsg xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id = "2470394108_TDF" > <connote action = "UN" > <consignmentNumber>2470394108</consignmentNumber><actionDate>2025-04-29T03:14:13.7700000</actionDate> <references><refType>Reference1</refType><refValue lang="en">11</refValue></references> <references><refType>Reference2</refType><refValue lang="en">12</refValue></references> <splInstructions></splInstructions><shipDate>2025-04-24T00:00:00</shipDate> <senderAccount>614060</senderAccount><senderName>TW-TGE-569575</senderName> <senderAddress> <addressLine1>245 KEVIN LIVINGSTON DRIVE</addressLine1><addressLine2></addressLine2><suburb>ISIS CENTRAL</suburb><state>QLD</state><country>AU</country><postCode>4660</postCode> </senderAddress> <receiverAccount>W09239</receiverAccount><receiverName>TW1</receiverName> <receiverAddress> <addressLine1>100 TODD RD</addressLine1><suburb>PORT MELBOURNE</suburb><state>VIC</state><country>AU</country><postCode>3207</postCode> </receiverAddress> <receiverReadyTime></receiverReadyTime><receiverClosingTime>1700</receiverClosingTime> <involvedParties> <partyRole>billTo</partyRole><partyAccount>614060</partyAccount><partyName>TW-TGE-569575</partyName> <partyAddress> <addressLine1>245 KEVIN LIVINGSTON DRIVE</addressLine1><addressLine2></addressLine2><suburb>ISIS CENTRAL</suburb><state>QLD</state><postCode>4660</postCode> </partyAddress></involvedParties> <totalItems>3</totalItems> <totalCubic UOM = "m">0.005</totalCubic> <totalWeight>168</totalWeight> <isFood>false</isFood> <serviceType>General</serviceType> <mode>ROAD</mode> <expectedDeliveryDate>2025-05-01T00:00:00.000+00:00</expectedDeliveryDate> <busunit>TNQX</busunit> <additionalAttributes><attribName>tesFlg</attribName><attribValue>0</attribValue></additionalAttributes> <additionalAttributes><attribName>tesAmt</attribName><attribValue>0.00</attribValue></additionalAttributes> <additionalAttributes><attribName>quoteNo</attribName><attribValue>0</attribValue></additionalAttributes> </connote> <srcSystem>TW</srcSystem> </connoteMsg>',
        "TS": None
    }
]
